- pom.xml
- src/main/resources/application.yml
> fix feature login

- frontend/react/src/component/Authentication/Login.jsx
- frontend/react/src/component/Authentication/Register.jsx
- frontend/react/src/component/LandingPage.jsx
- frontend/react/src/component/Shared/DashBoard.jsx
Create Landiing Page, Login and Register
> Thinhndhe160416

- src/main/java/com/nihongo/sep490g2fa24/exception/ApplicationExceptionHandler.java
cứ pull đi chỉ comment để test thôi
> test thôi nhé

- src/main/java/com/nihongo/sep490g2fa24/exception/NhgErrorHandler.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/AuthenServiceImpl.java
- src/main/resources/messages.properties
try catch wrong username, password
> Try catch wrong username and password

- src/main/java/com/nihongo/sep490g2fa24/exception/ApplicationExceptionHandler.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/AuthenService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/AuthenServiceImpl.java
- src/main/resources/messages.properties
Handle invalid password return http status 
401 unauthorized to FE
> Handle invalid password return http status 401 unauthorized to FE

- frontend/react/src/component/Authentication/Register.jsx
- frontend/react/src/component/LandingPage.jsx
- src/main/java/com/nihongo/sep490g2fa24/v1/model/User.java
modify length email, fix sonar, modify landing page
> modify length email and fix sonar

- src/main/java/com/nihongo/sep490g2fa24/exception/NhgErrorHandler.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/AuthenController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/request/ChangePasswordRequest.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/AuthenService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/AuthenServiceImpl.java
- src/main/resources/messages.properties
> Phuocnhhe163692

- src/main/java/com/nihongo/sep490g2fa24/v1/event/listener/RegistrationCompleteEventListener.java
- src/main/resources/application.yml
> modify feature login and register, authen email

- pom.xml
- src/main/java/com/nihongo/sep490g2fa24/config/SecurityConfig.java
- src/main/java/com/nihongo/sep490g2fa24/exception/NhgErrorHandler.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/UserController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/AuthenServiceImpl.java
- src/main/resources/messages.properties
Test api user
Test authentication for user
Fix bug login without verify email after register
> Fix bug login

- frontend/react/src/component/Authentication/ChangePassword.jsx
- src/main/java/com/nihongo/sep490g2fa24/config/SecurityConfig.java
- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/CourseDTOMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/CourseController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/course/CourseDTO.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/Course.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/CourseRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/CourseService.java
> Update course BE

- frontend/react/src/component/Authentication/ChangePassword.jsx
- frontend/react/src/component/Course/CourseCard.jsx
- frontend/react/src/component/Layout/Sidebar/SideBar.jsx
- frontend/react/src/component/Shared/DashBoard.jsx
Modify Course and DashBoard Again
> Modify Course and DashBoard

- frontend/react/package.json
- frontend/react/src/App.jsx
- frontend/react/src/component/Demo/Alphabets
- frontend/react/src/component/Demo/Alphabets.jsx
- frontend/react/src/component/Layout/Sidebar/SideBar.jsx
Fix and update demo alphabet FE
> Update Alphabets FE

- frontend/react/src/component/Quiz/Quizview.jsx
> Modify Quiz View

- frontend/mockDara.js
- frontend/react/src/App.jsx
Update data and path config, add file mockDara.js
> Update data and path config

- src/main/java/com/nihongo/sep490g2fa24/exception/NhgErrorHandler.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/course/CourseDTO.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/Course.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/Lession.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/CourseRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/CourseService.java
- src/main/resources/messages.properties
Fix bugs and update api course
> Update course api

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/LessonMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/CourseController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/Grammar.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/LessonRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/LessonService.java
> Modify Course and Lesson

- src/main/java/com/nihongo/sep490g2fa24/v1/model/Vocabulary.java
> Modify Vocabulary

- frontend/react/src/App.jsx
- frontend/react/src/Course.jsx
- frontend/react/src/component/Achievement/Achievements.jsx
- frontend/react/src/component/Alphabet/Alphabet.jsx
- frontend/react/src/component/Course/CourseCard.jsx
- frontend/react/src/component/Course/Crud/AddCourseDialog.jsx
- frontend/react/src/component/Layout/DashBoardLayout.jsx
- frontend/react/src/component/Management/Crm.jsx
- frontend/react/src/component/Management/User/CustomersPage.jsx
- frontend/react/src/component/Shared/DashBoard.jsx
Add achievements, customerpage, coursedialog and update dashboard
> Update Course and Dashboard

- frontend/mockDara.js
- frontend/react/src/component/Authentication/Login.jsx
- frontend/react/src/component/Course/Crud/DeleteCourseDialog.jsx
- frontend/react/src/component/Course/Crud/EditCourseDialog.jsx
- frontend/react/src/component/FlashCard/FlashcardContext.jsx
- frontend/react/src/component/FlashCard/FlashcardEditor.jsx
- frontend/react/src/component/FlashCard/FlashcardSetList.jsx
- frontend/react/src/component/FlashCard/FlashcardStudy.jsx
- frontend/react/src/component/Layout/Header/Header.jsx
- frontend/react/src/component/Lesson/LessonDetail.jsx
- frontend/react/src/component/Record/ProgressContext.jsx
- frontend/react/src/main.jsx
Add new CourseDialog file and Flashcard file, fix bug and update data in course
> Update Course and Flashcard FE

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/GrammarMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/GrammarController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/GrammarRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/GrammarService.java
> Modify Grammar

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/KanjiMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/KanjiController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/KanjiRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/KanjiService.java
> Modify Kanji backend

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/FlashcardSetMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/FlashcardSetController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/course/FlashcardSetDTO.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/FlashcardSetRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/FlashcardSetService.java
> Modify FlashCard Set

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/TestMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/TestController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/course/TestDTO.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/TestRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/TestService.java
> Update Test for BE

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/TestQuestionMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/FlashcardController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/course/TestQuestionDTO.java
Update TestQuestion and Flashcard BE
> Update TestQuestion and Flashcard BE

- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/AuthenController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/TestService.java
Fix and Modify Test and Authen
> Fix and Modify Test and Authen

- frontend/react/src/component/Management/Crm.jsx
- frontend/react/src/component/Management/Lesson/LessonDetailTabs.jsx
- frontend/react/src/component/Management/Lesson/LessonModal.jsx
- frontend/react/src/component/Management/Lesson/LessonPage.jsx
- frontend/react/src/component/Shared/Toast.jsx
- frontend/react/src/context/ToastProvider.jsx
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/CourseController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/LessonController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/LessonService.java
Fix Bug and Modify Lesson CRUD
> Fix Bug and Modify Lesson CRUD

- frontend/react/src/main.jsx
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/FlashcardSetController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/course/FlashcardSetDTO.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/FlashcardSet.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/FlashcardSetService.java
Update FlashcardSet for backend
> Update FlashcardSet BE

- frontend/react/src/App.jsx
- frontend/react/src/component/Demo/Blog.jsx
> Update App.jsx FE

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/UserAnswerMapper.java
- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/UserProgressMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/UserAnswerController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/UserProgressController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/dtos/course/UserProgressDTO.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/UserAnswer.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/UserProgress.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/UserAnswerRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/UserProgressRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/UserAnswerService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/UserProgressService.java
Modify User answer and User response
> Modify User answer and User response

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/TestResultMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/UserProgressController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/UserAnswerRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/UserProgressRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/AuthenService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/UserAnswerService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/UserProgressService.java
> Modify User Progress

- frontend/react/src/component/Management/Crm.jsx
> Modify png

- frontend/react/src/component/Lesson/LessonList.jsx
- frontend/react/src/component/Management/Crm.jsx
- frontend/react/src/component/Management/Question/QuestionList.jsx
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/FlashcardController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/Achievement.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/Lesson.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/QuestionOption.java
- src/main/java/com/nihongo/sep490g2fa24/v1/model/UserAchievement.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/FlashcardRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/LessonRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/FlashcardService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/LessonService.java
- src/main/resources/application.yml
+ Tạo 1 file mới trong file explore để tên là image
ví dụ: C:\ image
+ Copy as path rồi patse vào yml và lessonService
> đã thông luồng (nhớ fix môi trường)

- frontend/react/src/App.jsx
- frontend/react/src/component/Blog/Crud/CreateBlog.jsx
- frontend/react/src/component/Blog/Crud/ListBlog.jsx
- src/main/java/com/nihongo/sep490g2fa24/v1/model/Vocabulary.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/CourseService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/FlashcardService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/FlashcardSetService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/GrammarService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/KanjiService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/LessonService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/TestQuestionService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/TestService.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/VocabularyService.java
> Validate all Fields

- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/GrammarMapper.java
- src/main/java/com/nihongo/sep490g2fa24/dtoMapper/LessonMapper.java
- src/main/java/com/nihongo/sep490g2fa24/v1/controllers/VocabularyController.java
- src/main/java/com/nihongo/sep490g2fa24/v1/repositories/GrammarRepository.java
- src/main/java/com/nihongo/sep490g2fa24/v1/services/impl/GrammarService.java
> Modify final
